#!/usr/bin/env python3
"""
Process Instagram data export into photowall-ready format.
- Reads posts_1.json for captions + timestamps
- Copies images to public/photowall/ (skips videos)
- Converts .webp to .jpg
- Generates src/lib/photowall-data.ts with all post metadata
"""

import json
import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INSTA_BASE = ROOT / "Images" / "Instagram"
POSTS_JSON = INSTA_BASE / "your_instagram_activity" / "media" / "posts_1.json"
MEDIA_BASE = INSTA_BASE / "media"
OUT_DIR = ROOT / "public" / "photowall"
TS_OUT = ROOT / "src" / "lib" / "photowall-data.ts"

def fix_encoding(text: str) -> str:
    """Fix Instagram's broken UTF-8 encoding (stored as latin-1 code points)."""
    try:
        return text.encode('latin-1').decode('utf-8')
    except (UnicodeDecodeError, UnicodeEncodeError):
        return text

def process():
    # Load posts
    with open(POSTS_JSON, "r") as f:
        posts = json.load(f)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    entries = []
    copied = 0
    skipped_video = 0
    skipped_missing = 0

    for post_idx, post in enumerate(posts):
        media_items = post.get("media", [])
        post_images = []

        for media in media_items:
            uri = media.get("uri", "")
            # Skip videos
            if uri.endswith(".mp4") or uri.endswith(".srt"):
                skipped_video += 1
                continue

            src = MEDIA_BASE.parent / uri  # uri is relative to Instagram/
            if not src.exists():
                # Try from MEDIA_BASE directly
                src = MEDIA_BASE / "/".join(uri.split("/")[1:])  # strip "media/" prefix
            if not src.exists():
                skipped_missing += 1
                continue

            # Determine output filename
            stem = src.stem
            if src.suffix.lower() == ".webp":
                out_name = f"{stem}.jpg"
            else:
                out_name = src.name

            dst = OUT_DIR / out_name

            if not dst.exists():
                if src.suffix.lower() == ".webp":
                    # Convert webp to jpg using sips (macOS)
                    try:
                        # Copy as-is first, Next.js Image can handle webp
                        shutil.copy2(src, OUT_DIR / src.name)
                        out_name = src.name  # keep as webp, Next handles it
                        dst = OUT_DIR / out_name
                    except Exception as e:
                        print(f"  Error copying {src}: {e}")
                        continue
                else:
                    shutil.copy2(src, dst)

            copied += 1

            caption = fix_encoding(media.get("title", ""))
            timestamp = media.get("creation_timestamp", 0)

            post_images.append({
                "filename": out_name,
                "caption": caption,
                "timestamp": timestamp,
            })

        if post_images:
            # Use first image's timestamp for the post
            ts = post_images[0]["timestamp"]
            # Use first caption found (sometimes only first image has it)
            caption = ""
            for img in post_images:
                if img["caption"]:
                    caption = img["caption"]
                    break

            entries.append({
                "id": f"post_{post_idx}",
                "images": [img["filename"] for img in post_images],
                "caption": caption,
                "timestamp": ts,
                "date": datetime.fromtimestamp(ts).strftime("%Y-%m-%d") if ts else "",
            })

    # Sort by timestamp descending (newest first)
    entries.sort(key=lambda e: e["timestamp"], reverse=True)

    # Generate TypeScript
    ts_lines = [
        "// Auto-generated by scripts/process-instagram.py",
        "// Do not edit manually",
        "",
        "export interface PhotoPost {",
        "  id: string;",
        "  images: string[];",
        "  caption: string;",
        "  timestamp: number;",
        "  date: string;",
        "}",
        "",
        f"export const posts: PhotoPost[] = {json.dumps(entries, indent=2, ensure_ascii=False)};",
        "",
        f"export const totalPosts = {len(entries)};",
    ]

    with open(TS_OUT, "w") as f:
        f.write("\n".join(ts_lines))

    print(f"✅ Processed {len(entries)} posts ({copied} images copied)")
    print(f"   Skipped: {skipped_video} videos, {skipped_missing} missing files")
    print(f"   Output: {OUT_DIR}")
    print(f"   Manifest: {TS_OUT}")

if __name__ == "__main__":
    process()
